export default {
    ADD_TODO_ITEM: 'ADD_TODO_ITEM',
    DELETE_TODO_ITEM: 'DELETE_TODO_ITEM',
    DELETE_ALL: 'DELETE_ALL',
    EDIT_TODO: 'EDIT_TODO',
    SET_LOGIN_STATE: 'SET_LOGIN_STATE',
    GET_USER_INFO: 'GET_USER_INFO',
    GET_TODO_LIST: 'GET_TODO_LIST',
    DELETE_BY_KEY: 'DELETE_BY_KEY',
};